In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/nn/Downloads/Abhimanyu B/Datasets/Loan_Data.csv")

In [3]:
df.head()

LoanID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
df.isnull().sum()

LoanID                0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [5]:
df["Gender"].replace(["Male","Female"],[1,0],inplace=True)
df["Married"].replace(["Yes","No"],[1,0],inplace=True)
df["Education"].replace(["Graduate","Not Graduate"],[1,0],inplace=True)
df["Self_Employed"].replace(["Yes","No"],[1,0],inplace=True)
df["Property_Area"].replace(["Urban","Rural","Semiurban"],[0,1,2],inplace=True)
df["Loan_Status"].replace(["Y","N"],[1,0],inplace=True)

In [6]:
df.head()

LoanID  Gender  Married Dependents  Education  Self_Employed  \
0  LP001002     1.0      0.0          0          1            0.0   
1  LP001003     1.0      1.0          1          1            0.0   
2  LP001005     1.0      1.0          0          1            1.0   
3  LP001006     1.0      1.0          0          0            0.0   
4  LP001008     1.0      0.0          0          1            0.0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0              0            1  
1             1.0              1            0  
2             1.0              0            1  
3             1.0              0            1  
4             1.0              0            1

In [7]:
df["Property_Area"].unique()

array([0, 1, 2], dtype=int64)

In [8]:
df["Loan_Amount_Term"].unique()

array([360., 120., 240.,  nan, 180.,  60., 300., 480.,  36.,  84.,  12.])

In [9]:
df.drop(columns=["LoanID"],inplace=True)

In [10]:
df["Gender"]=df["Gender"].fillna(df["Gender"].median())
df["Married"]=df["Married"].fillna(df["Married"].median())
df["Self_Employed"]=df["Self_Employed"].fillna(df["Self_Employed"].median())
df["Loan_Amount_Term"]=df["Loan_Amount_Term"].fillna(df["Loan_Amount_Term"].median())
df["Credit_History"]=df["Credit_History"].fillna(df["Credit_History"].median())
df["LoanAmount"]=df["LoanAmount"].fillna(df["LoanAmount"].mean())

In [11]:
df.isnull().sum()

Gender                0
Married               0
Dependents           15
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [12]:
df["Dependents"].unique()

array(['0', '1', '2', '3+', nan], dtype=object)

In [13]:
df["Credit_History"].unique()

array([1., 0.])

In [14]:
df["Dependents"].replace(["3+"],[3],inplace=True)
df["Dependents"].unique()

array(['0', '1', '2', 3, nan], dtype=object)

In [15]:
df["Dependents"]=df["Dependents"].fillna(df["Dependents"].median())

In [16]:
df.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [17]:
df.head()

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
0     1.0      0.0          0          1            0.0             5849   
1     1.0      1.0          1          1            0.0             4583   
2     1.0      1.0          0          1            1.0             3000   
3     1.0      1.0          0          0            0.0             2583   
4     1.0      0.0          0          1            0.0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0  146.412162             360.0             1.0   
1             1508.0  128.000000             360.0             1.0   
2                0.0   66.000000             360.0             1.0   
3             2358.0  120.000000             360.0             1.0   
4                0.0  141.000000             360.0             1.0   

   Property_Area  Loan_Status  
0              0            1  
1              1            0  
2              0            1  
3              0            1  
4              0            1

In [18]:
X = df.drop(columns=["Loan_Status"])

In [19]:
y = df["Loan_Status"]

In [20]:
from sklearn.model_selection import train_test_split
X_test,X_train,y_test,y_train = train_test_split(X,y,test_size=0.20)

In [21]:
X_test.shape

(491, 11)

In [22]:
from sklearn.linear_model import LogisticRegression


In [23]:
model = LogisticRegression()

In [24]:
model.fit(X_train,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [25]:
y_pred = model.predict(X_test)

In [26]:
y_pred

array([1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [27]:
y_test

427    1
367    0
282    1
46     1
47     1
      ..
267    1
557    1
52     0
54     0
526    1
Name: Loan_Status, Length: 491, dtype: int64

In [28]:
data = pd.DataFrame({"actual":y_test,"predicted":y_pred})

In [29]:
data

actual  predicted
427       1          1
367       0          0
282       1          1
46        1          1
47        1          1
..      ...        ...
267       1          0
557       1          1
52        0          1
54        0          0
526       1          1

[491 rows x 2 columns]

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
cm = confusion_matrix(y_test,y_pred)

In [32]:
cm

array([[ 66,  90],
       [ 22, 313]], dtype=int64)

In [33]:
from sklearn.metrics import classification_report

In [34]:
cr = classification_report(y_test,y_pred)

In [35]:
print(cr)

              precision    recall  f1-score   support

           0       0.75      0.42      0.54       156
           1       0.78      0.93      0.85       335

    accuracy                           0.77       491
   macro avg       0.76      0.68      0.69       491
weighted avg       0.77      0.77      0.75       491

